#!/usr/bin/env python3
"""
Bundle the dnadis package into a single executable Python file.

This script concatenates all package modules into a single file that can be
distributed and run without installation:
    wget https://example.com/dnadis.py
    python dnadis.py --help

Usage:
    python scripts/bundle_single_file.py > dnadis_bundled.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path


# Define the order of modules to concatenate (dependencies first)
MODULE_ORDER = [
    # Models (no dependencies)
    ("dnadis/models.py", "dnadis.models"),
    # Utils (depend on nothing or each other)
    ("dnadis/utils/io_utils.py", "dnadis.utils.io_utils"),
    ("dnadis/utils/sequence_utils.py", "dnadis.utils.sequence_utils"),
    ("dnadis/utils/reference_utils.py", "dnadis.utils.reference_utils"),
    # Alignment (depends on utils)
    ("dnadis/alignment/external_tools.py", "dnadis.alignment.external_tools"),
    ("dnadis/alignment/chain_parsing.py", "dnadis.alignment.chain_parsing"),
    ("dnadis/alignment/stats.py", "dnadis.alignment.stats"),
    # Detection (depends on utils, models, alignment)
    ("dnadis/detection/blast.py", "dnadis.detection.blast"),
    ("dnadis/detection/organelle.py", "dnadis.detection.organelle"),
    ("dnadis/detection/rdna.py", "dnadis.detection.rdna"),
    ("dnadis/detection/debris.py", "dnadis.detection.debris"),
    ("dnadis/detection/contaminant.py", "dnadis.detection.contaminant"),
    # Classification (depends on utils, models, detection)
    ("dnadis/classification/classifier.py", "dnadis.classification.classifier"),
    # Output (depends on utils, models)
    ("dnadis/output/fasta_output.py", "dnadis.output.fasta_output"),
    ("dnadis/output/tsv_output.py", "dnadis.output.tsv_output"),
    ("dnadis/output/plotting.py", "dnadis.output.plotting"),
    # CLI (main entry point - depends on all modules)
    ("dnadis/cli.py", "dnadis.cli"),
]

# Patterns to remove from extracted modules
REMOVE_PATTERNS = [
    # Remove imports from the package (they'll be in the same file)
    r"^from dnadis\..*import.*$",
    r"^from dnadis_orig import.*$",
    # Remove shebang lines except for the first module
    r"^#!/usr/bin/env python3$",
    # Remove __future__ imports after the first
    r"^from __future__ import annotations$",
]


def read_module(path: Path) -> str:
    """Read a module file and return its content."""
    return path.read_text()


def clean_module_content(content: str, module_name: str, is_first: bool = False) -> str:
    """Remove package-specific imports and other items that shouldn't be in bundle."""
    lines = content.split("\n")
    cleaned_lines = []

    # Track if we're in a multi-line import
    in_multiline_import = False
    # Track if we're in the if __name__ == "__main__" block (skip it)
    in_main_block = False

    for line in lines:
        # Handle multi-line imports
        if in_multiline_import:
            if ")" in line:
                in_multiline_import = False
            continue

        # Handle if __name__ == "__main__" block (we add this at the end of bundle)
        if in_main_block:
            # Continue skipping until end of file (main block is always last)
            continue
        if line.startswith('if __name__ == "__main__"') or line.startswith("if __name__ == '__main__'"):
            in_main_block = True
            continue

        # Check if this starts a multi-line import from the package
        if re.match(r"^from dnadis[._]", line) and "(" in line:
            if ")" not in line:
                in_multiline_import = True
            continue

        # Skip single-line imports from the package
        if re.match(r"^from dnadis[._]", line):
            continue

        # Always skip shebang and __future__ (we add them at the top of bundle)
        if line.startswith("#!/usr/bin/env python"):
            continue
        if line.startswith("from __future__ import"):
            continue

        cleaned_lines.append(line)

    return "\n".join(cleaned_lines)


def bundle_package() -> str:
    """Bundle all package modules into a single file."""
    script_dir = Path(__file__).parent
    root_dir = script_dir.parent

    output_parts = []

    # Add header
    output_parts.append('''\
#!/usr/bin/env python3
"""
dnadis - Genome-wide subgenome distance analysis tool.

This is a bundled single-file version of the dnadis package.
Generated by scripts/bundle_single_file.py

For development, use the package version instead.
"""
from __future__ import annotations
''')

    # Add standard library imports (collected from all modules)
    output_parts.append('''
import argparse
import gzip
import math
import re
import shutil
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple


''')

    # Process each module
    for i, (module_path, module_name) in enumerate(MODULE_ORDER):
        full_path = root_dir / module_path
        if not full_path.exists():
            print(f"Warning: {full_path} not found, skipping", file=sys.stderr)
            continue

        content = read_module(full_path)

        # Clean the content
        is_first = (i == 0)
        cleaned = clean_module_content(content, module_name, is_first)

        # Remove standard library imports (we've already added them)
        cleaned = re.sub(r"^import (argparse|gzip|math|re|shutil|subprocess|sys)\s*$", "", cleaned, flags=re.MULTILINE)
        cleaned = re.sub(r"^from (collections|dataclasses|pathlib|typing) import.*$", "", cleaned, flags=re.MULTILINE)

        # Add a section marker
        if module_name:
            output_parts.append(f"\n# " + "=" * 70)
            output_parts.append(f"# Module: {module_name}")
            output_parts.append("# " + "=" * 70 + "\n")
        else:
            output_parts.append(f"\n# " + "=" * 70)
            output_parts.append(f"# Remaining code from: {module_path}")
            output_parts.append("# " + "=" * 70 + "\n")

        output_parts.append(cleaned)

    # Add the main guard
    output_parts.append('''

if __name__ == "__main__":
    main()
''')

    return "\n".join(output_parts)


def main():
    """Generate the bundled single-file script."""
    bundled = bundle_package()
    print(bundled)


if __name__ == "__main__":
    main()
